version: '3.6'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backendtestsdocker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
    ports:
      - "8090:8090"
    environment:
      SPRING_BOOT_PROFILE: docker
    depends_on:
      - postgres